import React from 'react';
import ReactDOM from 'react-dom';
import SearchBar from "./components/SearchBar";

const API_KEY = 'AIzaSyATS38RuWTxH2vL9QSu_NTjE5JXlU3MzgU';

/*Create a new component. And make it creates some HTML*/

/*Accept the HTML generated by the component and put it on the web*/


const App = () => (
    <div>
        <SearchBar/>
        We have our first component
    </div>
);

ReactDOM.render(<App/>, document.querySelector('.container'));